### ISSUE TITLE
Tag Editor button doesn't always appear

### ISSUE THREAD

**Issue by rakheshster** [urvanov-ru/crayon-syntax-highlighter#26]
Hi,

First off thanks a lot for creating this fork. I love Crayon and had been dreading moving away from it since it's been unsupported for a while. 

I still use the Classic Editor and I was on Crayon until I updated to WordPress 5.6 recently, after which the Tag Editor button in the toolbar broke. Googling around for that is how I found this fork, and since installing it the Tag Editor seems to work randomly. Sometimes a new post has it, sometimes it doesn't. Even if a new post has it, if I save a Draft then the toolbar button disappears. I can of course insert code via the tags, and Syntax Highlighting itself works fine, just that it's easier to just use the toolbar button as it's more friendly. Is this a known issue? Anything I can do to fix this? 

Thanks.

**Comment by urvanov-ru** [comment]
Thank you for reporting. I will try to fix it. But I need time.

**Comment by rakheshster** [comment]
Take your time! I am happy you are maintaining this plugin and there's a place I can report this issue to. For now I workaround by inserting tags manually.

**Comment by urvanov-ru** [comment]
@rakheshster  2.8.16 I think, I fixed it in 2.8.16. Does it work now?

**Comment by rakheshster** [comment]
Hi, thanks for getting back. Let me see how it works the next few days and I'll report back. I just updated to 2.8.20 now, and I haven't blogged the past few days so not sure if 2.8.16 made a difference. I did create a new post now, save and exit it, then go back to the draft and the Tag Editor still appears so that's better compared to before.

**Comment by rakheshster** [comment]
Sorry for the delay. Looking good so far, so I'll close the issue. Thanks for fixing this!
